vim.opt.modelines = 0
vim.opt.wrap = false
vim.opt.backup = false
vim.opt.swapfile = false
vim.opt.encoding = "utf-8"
vim.opt.laststatus = 2
vim.opt.visualbell = true
vim.opt.tabstop = 2
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.completeopt = "menu,menuone,noselect"
vim.opt.signcolumn = "no"
vim.opt.nu = true
-- vim.cmd("syntax off")
vim.cmd("colorscheme quiet")
vim.opt.termguicolors = true
vim.opt.background = "light"
